name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '../../src/submodules/open-instruct/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '../../src/submodules/open-instruct/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: true

      - uses: actions/checkout@v4

      - name: Build, Tag and Push the Docker image
        env:
          IMAGE_NAME: lukashinterleitner/master-thesis-data-science
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git submodule init
          git submodule update

          docker buildx bake --push

          docker push $IMAGE_NAME:${IMAGE_TAG::8}
          docker push $IMAGE_NAME:latest
